# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9-stretch
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
        
      - store_artifacts:
          path: ~/repo

      - save_cache:
          key: v1-repo-{{ .Revision }}
          paths:
            - ~/repo

  deploy_dev:
    docker:
      # specify the version you desire here
      - image: circleci/python:2.7.13

    working_directory: ~/repo/deploy

    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Revision }}

      - run:
          command: |
            sudo pip install -r requirements.txt

      - run:
          command: |
            sudo apt-get update
            sudo apt install rsync
            python docker_digitalocean.py dev

  deploy_prod:
    docker:
      # specify the version you desire here
      - image: circleci/python:2.7.13

    working_directory: ~/repo/deploy

    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Revision }}

      - run:
          command: |
            sudo pip install -r requirements.txt

      - run:
          command: |
            sudo apt-get update
            sudo apt install rsync
            python docker_digitalocean.py $PROD_ENV


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - hold_before_dev:
         type: approval
         requires:
           - build
      - deploy_dev:
          requires:
            - hold_before_dev
          filters:
            branches:
              only: master
      - hold_before_prod:
         type: approval
         requires:
           - deploy_dev
      - deploy_prod:
          requires:
            - hold_before_prod
          filters:
            branches:
              only: master


